[env:genericSTM32F103CB]
platform = ststm32
board = genericSTM32F103CB
framework = arduino

monitor_speed = 460800

build_type = release

; Upload method can be changed to stlink/jlink/serial as needed.
; upload_protocol = stlink
